# Generated by Django 5.2.4 on 2025-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_emails',
            field=models.BooleanField(default=False),
        ),
    ]
